# 规则描述：每天凌晨 4 点 (GMT+8) 执行一次，将最近 30 天没有活跃且非 BUG 的 ISSUE 关闭
name: Issue Close Inactive

on:
  schedule:
    - cron: "0 20 * * *"

env: # 设置环境变量
  TZ: Asia/Shanghai #时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need close
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
#          token: ${{ secrets.GF_TOKEN }}
          labels: 'inactive'
          inactive-day: 30
          exclude-labels: 'bug,$exclude-empty'
          close-reason: 'not active'